import json

crawl = {
    'yahoo': {
        "highlights": "https://news.yahoo.com/",
        "world": "https://news.yahoo.com/world/",
        "politics": "https://news.yahoo.com/politics/",
        "business": "",
        "entertainment": "",
        "health": "https://news.yahoo.com/health/",
        "science": "https://news.yahoo.com/science/",
        "technology": "",
        "search": "",
    },
    'huffpost': {
        "highlights": "https://www.huffpost.com/news/",
        "world": "https://www.huffpost.com/news/world-news",
        "politics": "https://www.huffpost.com/news/politics",
        "business": "",
        "entertainment": "https://www.huffpost.com/entertainment/",
        "health": "",
        "science": "",
        "technology": "",
        "search": "",
    },
    'cnn': {
        "highlights": "https://edition.cnn.com/",
        "world": "https://edition.cnn.com/world",
        "politics": "https://edition.cnn.com/politics",
        "business": "https://edition.cnn.com/business",
        "entertainment": "https://edition.cnn.com/entertainment",
        "health": "https://edition.cnn.com/health",
        "science": "",
        "technology": "",
        "search": "",
    },
    'nytimes': {
        "highlights": "https://www.nytimes.com/",
        "world": "https://www.nytimes.com/section/world",
        "politics": "https://www.nytimes.com/section/politics",
        "business": "https://www.nytimes.com/section/business",
        "entertainment": "",
        "health": "https://www.nytimes.com/section/health",
        "science": "https://www.nytimes.com/section/science",
        "technology": "https://www.nytimes.com/section/technology",
        "search": "",
    },
    'foxnews': {
        "highlights": "https://www.foxnews.com/",
        "world": "https://www.foxnews.com/world",
        "politics": "https://www.foxnews.com/politics",
        "business": "",
        "entertainment": "https://www.foxnews.com/entertainment",
        "health": "",
        "science": "",
        "technology": "",
        "search": "",
    },
    "nbcnews": {
        "highlights": "https://www.nbcnews.com/",
        "world": "",
        "politics": "",
        "business": "",
        "entertainment": "",
        "health": "",
        "science": "",
        "technology": "",
        "search": "",
    },
    "bbcnews": {
        "highlights": "https://www.bbc.com/news",
        "world": "",
        "politics": "",
        "business": "",
        "entertainment": "",
        "health": "",
        "science": "",
        "technology": "",
        "search": "",
    },
    "abcnews": {
        "highlights": "https://abcnews.go.com/",
        "world": "",
        "politics": "",
        "business": "",
        "entertainment": "",
        "health": "",
        "science": "",
        "technology": "",
        "search": "",
    },
    "miscellaneous": {
        "opinion": "https://www.nytimes.com/section/opinion",
    }
}

with open('crawl.json','w') as outfile:
    json.dump(crawl, outfile,indent=4)
